version: '3.8'
services:
  redis:
    image: redis:7.2.3-alpine
    ports:
      - 6379:6379
  example_web_server:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - RATE_LIMITER_REDIS_HOST=redis
      - RATE_LIMITER_REDIS_PORT=6379
      - RATE_LIMITER_REDIS_PASSWORD=
      - RATE_LIMITER_REDIS_DB=0
